name = "menuapp"
main = "cloudflare-worker/worker.js"
compatibility_date = "2025-11-27"

[triggers]
crons = ["* * * * *"]

[vars]
FIREBASE_PROJECT_ID = "sweets-c4f6b"
TWILIO_WHATSAPP_NUMBER = "whatsapp:+17179713753"
